### ISSUE TITLE
payara-micro:start does not deploy maven artifacts and related issues

### ISSUE THREAD

**Issue by marmots** [payara/ecosystem-maven#105]
I'm trying to use payara-micro:start in order to run my integration tests. I've reached it, but i think I've found some problems. 

Running only start, maven artifact is not deployed:

MAVEN configuration:
------------------------
```<!-- integration test requires documentconverter microservice to be started -->
<plugin>
	<groupId>fish.payara.maven.plugins</groupId>
	<artifactId>payara-micro-maven-plugin</artifactId>
	<version>1.0.5</version>
	<executions>
		<execution>
			<id>start-document-converter</id>
			<phase>pre-integration-test</phase>
			<goals>
				<goal>start</goal>
			</goals>
		</execution>
		<execution>
			<id>stop-document-converter</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>stop</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
	  <payaraVersion>${version.payara}</payaraVersion>
          <daemon>true</daemon>
		<deployArtifacts>
			<deployArtifact>
				<groupId>com.ba.dg</groupId>
				<artifactId>documentconverter</artifactId>
				<version>0.0.2</version>
				<type>war</type>
				<destFileName>ROOT.war</destFileName>
			</deployArtifact>
		</deployArtifacts>
		<commandLineOptions>
			<commandLineOption>
				<key>--port</key>
				<value>32154</value>
			</commandLineOption>
			<commandLineOption>
				<key>--noCluster</key>
			</commandLineOption>
		</commandLineOptions>
		<contextRoot>/</contextRoot>
	</configuration>
</plugin>
```

MAVEN command
--------------------
`mvn clean package payara-micro:start`

OUTPUT
---------
```[2019-06-12T14:43:22.021+0200] [] [INFORMACIËN] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1560343402021] [levelValue: 800]
{
    "Instance Configuration": {
        "Host": "DG-DVALLS.bonarea.com",
        "Http Port(s)": "32154",
        "Https Port(s)": "",
        "Instance Name": "payara-micro",
        "Instance Group": "no-cluster",
        "Deployed": [
        ]
    }
}
```

So, start does not deploy maven artifact.

In order to make it work i have to run bundle, that creates the uberjar deploying the maven artifact, and start then the server:

MAVEN configuration:
```<!-- integration test requires documentconverter microservice to be started -->
<plugin>
	<groupId>fish.payara.maven.plugins</groupId>
	<artifactId>payara-micro-maven-plugin</artifactId>
	<version>1.0.5</version>
	<executions>
		<execution>
			<id>start-document-converter</id>
			<phase>pre-integration-test</phase>
			<goals>
			  <goal>bundle</goal>
		          <goal>start</goal>
			</goals>
		</execution>
		<execution>
			<id>stop-document-converter</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>stop</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
	  <useUberJar>true</useUberJar>
		<payaraVersion>${version.payara}</payaraVersion>
		<daemon>true</daemon>
		<deployArtifacts>
			<deployArtifact>
				<groupId>com.ba.dg</groupId>
				<artifactId>documentconverter</artifactId>
				<version>0.0.2</version>
				<type>war</type>
				<destFileName>ROOT.war</destFileName>
			</deployArtifact>
		</deployArtifacts>
		<commandLineOptions>
			<commandLineOption>
				<key>--port</key>
				<value>32154</value>
			</commandLineOption>
			<commandLineOption>
				<key>--noCluster</key>
			</commandLineOption>
		</commandLineOptions>
		<contextRoot>/</contextRoot>
	</configuration>
</plugin>
```

MAVEN command:
--------------------
`mvn clean package payara-micro:bundle payara-micro:start`

OUTPUT:
----------
```[2019-06-12T14:48:01.090+0200] [] [INFORMACIÓN] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1560343681090] [levelValue: 800]
{
    "Instance Configuration": {
        "Host": "DG-DVALLS.bonarea.com",
        "Http Port(s)": "32154",
        "Https Port(s)": "",
        "Instance Name": "payara-micro",
        "Instance Group": "no-cluster",
        "Deployed": [
            {
                "Name": "documentconverter-0.0.2",
                "Type": "war",
                "Context Root": "/documentconverter-0.0.2"
            }
        ]
    }
}
```

Here the plugin isn't using `destFileName` property, but it creates the bundle correctly and starts the server deploying the artifact.

It would be nice to perform it in only one goal (start with deploy).
Fixing the `destFileName` property problem would be also apreciated.

Thanks,

**Comment by jGauravGupta** [comment]
Hi @marmots,

You may set the `useUberJar` element value to `true`, to start bundled uber-jar using `payara-micro:start` or set the `deployWar` element value to, `true` to deploy WAR using `payara-micro:start`.

Defining WAR GAV coordinates is not necessary in `deployArtifacts` element to deploy war.  
`configuration → deployArtifacts → artifactItem` element should be used to copy other dependencies under `MICRO-INF/deploy` folder which are not packaged in uber-jar or war.

**Comment by marmots** [comment]
Hi @jGauravGupta ,

the point is that it is an integration test, in a plain java utility project i'm testing a functionallity that requires a microservice to be started, this microservice is an independent project deployed in our internal nexus server (called documentconverter).

in order to see that all toghether performs well i need to start a payara-micro instance with this external project (not with the project i'm working on). So my best option is to get it via maven coordinates. Once started and deployed i run my tests in order to verify the whole system.

if i took out `bundle` goal mantaining `useUberJar` i get 'documentparser-0.0.6-SNAPSHOT-microbundle.jar does not exist. I need to execute the "bundle" goal before using this option.' So useUberJar needs bundle to be executed. `deployWar` is not an option as the project is an utility jar.

It's not a problem for me, it's working but i wonder if it will be possible to start payara-micro just telling maven coordinates, without the need of packaging the uberjar before.

The other thing is that `destFileName` is not used when deploying into the `uberjar` so i thouth it was a bug and i only wanted to report it. I'm telling to deploy it as ROOT.war -> `/` but i get it as documentconverter-0.0.2.war -> `/documentconverter-0.0.2`

I hope i'm communicating things correctly (english is not my motherlanguage).

**Comment by jGauravGupta** [comment]
Hi @marmots,

I understand and Payara Micro maven plugin `deployArtifacts` element is not designed for such a use-case.

I recommend using [Payara Micro Arquillian Connector](https://docs.payara.fish/documentation/ecosystem/arquillian-containers/payara-micro.html) for testing. You may choose any one of the following way and (2) is the most preferred way to test microservices.

1. Declare multiple @Deployment(name="microservice-x") WebArchive.
2. Test the main application in the arquillian container and deploy the microservices on Docker containers managed by cube extension.

**Comment by marmots** [comment]
Thank you. You just opened my mind to a world of possibilities. I use Arquillan for the Junit's but I had not thought about using it for the IT's also... I will get much more control.
