### ISSUE TITLE
introduce development branch or keep master at next snapshot

### ISSUE THREAD

**Issue by emattheis** [payara/ecosystem-maven#107]
As a recent contributor, I noticed that although my PR was accepted into master, the version in the POM still matches the release version. If master is going to be the working branch from which releases are tagged, I suggest keeping the version number tracking the next release - (e.g. 1.0.6-SNAPSHOT). Alternatively, a development branch could be introduced to track the next release and master could remain in sync with the latest release.

**Comment by jGauravGupta** [comment]
Fixed by https://github.com/payara/ecosystem-maven/pull/109, thanks for pointing out.
