### ISSUE TITLE
No cooperation between stop goal of plugin and payara micro 5.193

### ISSUE THREAD

**Issue by pzygielo** [payara/ecosystem-maven#118]
Following warning is reported from plugin's stop goal execution:
```
[INFO] --- payara-micro-maven-plugin:1.0.6:stop (stop-payara) ---

JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]

[WARNING] Could not stop previously started payara-micro with process ID 4395 or waiting too long, proceeding further
```

**Comment by pzygielo** [comment]
It seems that increasing 
https://github.com/payara/ecosystem-maven/blob/d1b5a14be4af77d8d52615d46d838048bd4bfec8/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/Configuration.java#L65 would be enough to make plugin happy.
Perhaps configuration for that param referenced in https://github.com/payara/ecosystem-maven/blob/d1b5a14be4af77d8d52615d46d838048bd4bfec8/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StopMojo.java#L167 could be considered?

**Comment by jGauravGupta** [comment]
Thanks for the PR https://github.com/payara/ecosystem-maven/pull/119

**Comment by pzygielo** [comment]
Seems related - https://github.com/payara/Payara/pull/4250
