### ISSUE TITLE
Missing tag for payara-micro-maven-plugin 1.1.0 release

### ISSUE THREAD

**Issue by pzygielo** [payara/ecosystem-maven#155]
Could you tag repository for payara-micro-maven-plugin 1.1.0 release available in central, please?

**Comment by jGauravGupta** [comment]
Both payara-micro-maven-plugin v1.1.0 & payara-micro-maven-archetype v1.1.0 released. And moving forward the single tag will be used for all tools in this repository.

**Comment by pzygielo** [comment]
Thanks for checking and for details on tagging releases plan.
:+1:
