### ISSUE TITLE
copySystemProperties causes system properties to be used as environment variables

### ISSUE THREAD

**Issue by ljnelson** [payara/ecosystem-maven#19]
Hi; thanks for your work on a great product.  I found the following to be quite confusing:

The `copySystemProperties` parameter, if `true`, causes the [Maven session's property names](https://maven.apache.org/ref/3.5.0/maven-core/apidocs/org/apache/maven/execution/MavenSession.html#getSystemProperties()) to be used as if they were the names of "true" System properties (they're not required to be), then retrieves corresponding "true" System property values under those names, and [creates a collection of Strings in `name=value` format](https://github.com/payara/maven-plugins/blob/1.0.0/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java#L109).  This collection is then [passed to the `Runtime.exec()` method as the value for its environment variables parameter](https://github.com/payara/maven-plugins/blob/1.0.0/payara-micro-maven-plugin/src/main/java/fish/payara/maven/plugins/micro/StartMojo.java#L132-L133).

The net effect is:
* The value of a Maven session system property, which is not necessarily a System property value, is ignored.  (For example, one of the properties that might show up here could be named `env.HOME`; there is no such "true" System property.)
* A System property value indexed under that name is used instead, if it exists.
* the Payara Micro process spawned by this plugin is run with environment variables named after those property names and holding values of the JVM's System properties corresponding to those names

If I have time I'll supply a pull request later.  Thanks again for Payara!

**Comment by mulderbaba** [comment]
internal issue MP-20

**Comment by mulderbaba** [comment]
Closed by #59
