### ISSUE TITLE
Enable running WAR artifact out of the box with default configuration

### ISSUE THREAD

**Issue by OndroMih** [payara/ecosystem-maven#53]
Currently, the payara-micro:start goal needs `deployWar=true` to start with the built artifact.

*Current state:*

The only way to configure this is in the goal configuration, which requires modifying pom.xml. See an example project: https://github.com/payara/Payara-Examples/blob/master/ecosystem/maven-plugin-base-example/pom.xml

*Desired state:*

Possible to run a WAR maven artifact without adding any configuration in pom.xml. With a vanilla WAR maven project, it should be possible to run it with Payara Micro with maven from command line, like this:

```
mvn package payara-micro:start
```

This would require to change the default value of the `deployWar` option so that it defaults to `true` and not to `false` as now. 

Alternatively, `deployWar` should be configurable with a system property, which can be supplied on command line. For example, this would be acceptable if we decide to maintain backward compatibility:

```
mvn -Dfish.payara.micro.deployWar=true payara-micro:start
```

But I would rather break compatibility to get users started easily without any additional configuration.

**Comment by gilbertoca** [comment]
When I saw how to stop the plugin I've given up on it immediately

**Comment by mulderbaba** [comment]
@gilbertoca can you elaborate your use case for us please? Stopping a running payara-micro with the plugin is as simple as: `mvn payara-micro:stop`(Assuming that you already defined the plugin in your plugins section.)

**Comment by gilbertoca** [comment]
What about Ctrl + D/C or better enter QUIT/EXIT on the terminal instead of opening another terminal to initiate a new maven process?

**Comment by mulderbaba** [comment]
@gilbertoca it's always an option and you don't need a maven process as well to start the micro. What about you are executing with `daemon` mode and you want to stick with the maven lifecycle?

**Comment by gilbertoca** [comment]
I understand! I visualize that you need STOP goal when you execute the START one and not when you, maybe, execute 
`mvn package payara-micro:run`

So, I think I'm very used to [TomEE Embedded Maven Plugin](http://tomee.apache.org/tomee-embedded-maven-plugin.html)

**Comment by mulderbaba** [comment]
@gilbertoca that should not be possible.

**Comment by fturizo** [comment]
Older issue that seems to be abandoned, closing.
