### ISSUE TITLE
Support for the contextRoot option of 5.191

### ISSUE THREAD

**Issue by rdebusscher** [payara/ecosystem-maven#81]
The new `contextroot` option is described [here](https://docs.payara.fish/documentation/payara-micro/deploying/deploy-cmd-line.html#define-context-root).

add <contextRoot> configuration parameter within the maven plugin for

## bundle goal
To deploy the application to a specific context root

## start goal
To deploy the application to a specific context root

**Comment by mulderbaba** [comment]
fixed by #83
